#----------------------------------------------------------------------------
# GLOBAL VARIABLES
#----------------------------------------------------------------------------
runs = ["run1", "run2", "run3"]
configfile: 'config/config.yaml'
CHROMS = ['chr' + str(i) for i in range(1,23)] # this will need to change if we want to include x or y chromosomes

#----------------------------------------------------------------------------
# MODULES / RULES
#----------------------------------------------------------------------------

include: 'rules/alignment.smk'
include: 'rules/call_variants.smk'
include: 'rules/analysis.smk'

#----------------------------------------------------------------------------

# MISC